### ISSUE TITLE
Reimplement "Remove Old Kernel" tweak.

### ISSUE THREAD

**Issue by isantolin** [folkswithhats/fedy#167] opened 2015-05-19 04:12 UTC
Is "Remove Old Kernel" option missing. Bug?

**Comment by satya164** [comment] 2015-05-19 09:29
Another feature implementation is needed before I can add plugins which need confirmation dialogs etc. It'll take some time. You can do the following for now,

```
sudo package-cleanup -y --oldkernels --count=1
```

**Comment by Abhinav1217** [comment] 2015-06-05 02:37
Is there a better way to remove old kernel in Fedora since `package-cleaner` which is part of yum-utils is now marked deprecated in fedora 22, And dnf remove kernel will remove all the kernel including the running one.

**Comment by satya164** [comment] 2015-06-05 12:29
@Abhinav1217 You can do the following,

`sudo dnf erase $(dnf repoquery --installonly --latest-limit -2 -q)`

**Comment by Abhinav1217** [comment] 2015-06-07 12:47
not working.. it did nothing for more than 15minutes till I terminated it.
`dnf repoquery --installonly --latest-limit -2 -q` did nothing also..  

```
[Abhinav@abhinav-fed22 ~] $ sudo dnf erase $(dnf repoquery --installonly --latest-limit -2 -q)
Error: Need to pass a list of pkgs to remove
 Mini usage:

remove PACKAGE...

Remove a package or packages from your system

alias: erase
[Abhinav@abhinav-fed22 ~] $ 

```

**Comment by satya164** [comment] 2015-06-07 12:47
@Abhinav1217 Try using sudo.

**Comment by Abhinav1217** [comment] 2015-06-07 12:51
Two. Missed that fact out. Let me try with `-1`

**Comment by Abhinav1217** [comment] 2015-06-07 12:55
Worked perfectly, But unlike package-cleanup, it only removed the kernel, not kernel-header and kernel-devel.  I love dnf better than yum since i used it to install gnome 3.12 in f20, but I hate their decision to remove the utility to remove even the running kernel.

**Comment by Abhinav1217** [comment] 2015-06-08 02:45
Bad news, But it didn't work perfectly. When I rebooted the system this morning, I could see the older entries in the grub. So I used Fedy's Grub configuration tweak, and rebooted,  The old entries are still there.  Any suggestion?

**Comment by TrustyWolf** [comment] 2015-12-06 11:23
@satya164 Thanks! The best way to remove old kernels @Fedora23

**Comment by Abhinav1217** [comment] 2015-12-06 13:22
The above command works fine for me.  But I have sometime found kernel-devel to be left behind.   Also I have needed to rebuild grub.  

Past few months, I am removing kernel manually.  i do `dnf list --install-only kernel-core` to list all the kernels and then do `dnf erase kernel-core-xxxx` which removes kernel and kernel-headers kernel-modules etc.

**Comment by genodeftest** [comment] 2016-05-08 16:22
I'd rather edit `/etc/dnf/dnf.conf` and set `installonly_limit=2`. This solution is pretty clean and well-tested.

By the way: It is an intended feature to have more than one kernel installed. This way, if the new kernel fails you may still be able to boot the old kernel.

**Comment by danstewart** [comment] 2017-03-14 03:22
@satya164 @Abhinav1217 What did this tweak do? Just delete old kernels apart from the latest two?
Looks like the current default is 3 - does Fedora not clean old kernels up by default?

**Comment by Abhinav1217** [comment] 2017-03-14 07:24
Fedora used to keep lots of old kernels. DNF is now set to 5 old kernels, I had manually changed it to 1 old kernel which is the lowest it allows. 

It is recommended to have few old kernels but many find it unnecessary, specially if they have dual boot or multiboot system, there will be lots of entries and wasted disk space.  Earlier yum could remove all the kernels except the latest one, so there would be only one fedora entry on boot menu.  

Maybe we should merge this with another old tweak plugin `configure yum to keep cache` and create a new `Configure DNF` tweak plugin. 

This new plugin will configure dnf with recommended popular tweaks, like setting `installonly_limit` to 2, enabling cache ( which was not enabled by default up untill F24 but not it seems it is enabled in F25, I will check and report ), and some other tweaks suggested by internet.

**Comment by satya164** [comment] 2017-03-14 08:35
> What did this tweak do?

Not much. here is the code https://github.com/folkswithhats/fedy/blob/01fd1aabff718e3e40a01d2702f27bdf4cf5d72d/plugins/misc/rem_oldkernels.sh

**Comment by bddenhartog** [comment] 2017-07-18 18:32
Closing this due to irrelevance.

Fedora keeps 3 kernels by design and default; users who wish to change this can update their dnf configuration.

**Closed by bddenhartog** 2017-07-18 18:32 UTC
Labels: area:plugins, type:feature
