### ISSUE TITLE
Installing chrome produces no visible Launcher

### ISSUE THREAD

**Issue by thawkins** [folkswithhats/fedy#431] opened 2017-01-29 23:29 UTC
When installing chrome via fedy latest on fedora 25 fully updated, the installer runs to completion, but does not add any Launcher. 

a subsequent 

$sudo dnf reinstall google-chrome-stable 

Produces an install with a Launcher

Note: a Launcher for the "ChromeApps" thingy that allows you to run extensions separate from chrome is installed. 

opening a terminal and typing 

$google-chrome &

also works, so the chrome package has been successfully installed. 

This has happened on two separate Fedora 25 Installs.

**Comment by Abhinav1217** [comment] 2017-01-30 07:13
Didn't google retire it. https://blog.chromium.org/2016/03/retiring-chrome-app-launcher.html. 
As for separate chrome app launching, They are all available in the OS's app menu. Look at the screenshot of my Gno-menu where you can see chrome app category.

![Gno-menu Chrome app category](https://cloud.githubusercontent.com/assets/740584/22414780/4fe8fa24-e6e8-11e6-8698-bfbaff0a6edf.png)

 and My Gnomes app screen where you can see some chrome apps between rest of my apps.

![Chrome apps seen on gnome-shell apps screen](https://cloud.githubusercontent.com/assets/740584/22414781/4fe968ce-e6e8-11e6-87f2-17f64d4afbd7.png)

I can launch Apps directly from my menu.   This was the reason why chrome stopped app launcher.

If you are on wayland there is a problem with tray icon ( its api has been removed from wayland ) which causes chrome sometimes not to run in background. You have to play with chrome flags for its issue as they claim they support wayland.  I switched to XORG session and you can see in the screenshot legacy icons, Chrome is running in background.

![screenshot from 2017-01-30 12-40-56](https://cloud.githubusercontent.com/assets/740584/22414944/ae61533e-e6e9-11e6-9f77-05cc9ef7cdcc.png)

**Comment by bddenhartog** [comment] 2017-02-16 01:15
@Abhinav1217 To clarify, @thawkins is talking about the `.desktop` file for Chrome that should be produced when installing via Fedy. I've tested and confirmed this bug.

**Comment by loop0** [comment] 2017-02-18 20:16
I can also confirm this bug. Installed Fedora 25, installed Fedy and then installed chrome, but no way to open it, only by executing `/opt/google/chrome/chrome` directly.

**Comment by Abhinav1217** [comment] 2017-02-20 05:40
I tested it several times last night, I couldn't reproduced it. I get desktop entries and menu entries everytime on Gnome, KDE, and XFCE. Even used a fresh Gnome-F25.  

@loop0 Can you give me your terminal output by running fedy via terminal and then running the plugin.

**Comment by Abhinav1217** [comment] 2017-02-20 05:47
@bddenhartog Can you also give your terminal output, Since I can't reproduce it on both wayland and xorg.
Are you using wayland or xorg.

thawkins mentioned

> Note: a Launcher for the "ChromeApps" thingy that allows you to run **extensions separate from chrome is installed**. 
That is why I assumed it was talking about the chrome launcher which used to be installed with chrome, acting as a application menu for chrome apps.

**Comment by bddenhartog** [comment] 2017-03-03 04:43
@Abhinav1217 The only output is from the packages installed via `dnf`. I've narrowed the issue down to [these lines](https://github.com/folkswithhats/fedy/blob/master/plugins/chrome.plugin/install.sh#L8-L17), which add a `StartupWMClass` parameter to all three service groups. 

For some reason, my `/usr/share/applications/google-chrome.desktop` file had two `StartupWMClass` definitions _above_ the first service groups, rendering the file invalid, which caused the file to error on parsing when `gnome` read it.

**Comment by Abhinav1217** [comment] 2017-03-03 08:06
It is confusing. I don't have `StartupWMClass` definition on my .desktop file. I did fresh install in a Gnome and KDE vm and found that there in KDE there is a definition and it is proper, but on Gnome there is none. 

I ran the fixer portion of the script directly on command line and then I have definitions on Gnome VM but not no my host gnome DE.

**Comment by bddenhartog** [comment] 2017-03-03 19:55
I've determined the issue: It appears the section names were changed at some point, so `grep` and `sed` don't match on anything. I've got a working local fix that I'll create a PR for shortly, with additional modifications to help protect against changes like this in the future (and provide error messages so we have useful debugging output in the event we fail to add the `StartupWMClass` entries for the sections we expect.

**Comment by bddenhartog** [comment] 2017-03-07 21:55
Closing manually because the commit referencing this issue did not contain a properly formatted message to auto-close when merged, and no "closes x" message was added to the merge commit.

**Closed by bddenhartog** 2017-03-07 21:55 UTC
Labels: area/plugins, type/bug (confirmed)
