### ISSUE TITLE
missing google gpg key

### ISSUE THREAD

**Issue by valentt** [folkswithhats/fedy#568] opened 2017-12-30 13:58 UTC
When installing google-talk plugin you also need to install google gpg key.

Currently gpg key is missing and this breaks updates which won't update any package if there is any package from unsigned repository.

Here is a forum post that helped me to manually fix this:
https://forums.mageia.org/en/viewtopic.php?t=11095&p=64491

Please add Google gpg key automatically when adding google repo with google-talk plugin. Thanks!

**Comment by bddenhartog** [comment] 2018-01-27 18:40
Do you mean the plugin for Hangouts? I've just tested this, and was unable to reproduce your issue. If you encounter the error again, please launch `fedy` from the command line, and paste the entire output within a code block.

**Comment by bddenhartog** [comment] 2018-01-27 18:43
I see that while the plugin installed successfully, we _did_ fail to import the key. This prevents upgrading the `google-talkplugin` package, as mentioned in the first comment.

Thanks for the issue! Sorry for the preemptive close :)

**Comment by bddenhartog** [comment] 2018-03-20 20:35
This was fixed by #578 and merged into master at b0a5e391d160e9a029f67f794c083501f9cd9be3

**Closed by bddenhartog** 2018-03-20 20:35 UTC
Labels: area:plugins, state:approved, type:bug
