### ISSUE TITLE
Fedora 26 Support

### ISSUE THREAD

**Issue by 0xMatt** [folkswithhats/fedy#459] opened 2017-07-07 23:14 UTC
I know a version 26 issue was opened almost 4mo ago, but I figured I'd make an official issue regarding the status of 26 support in general, especially since it'll be released in 4 days.

When could we expect a a build targeted for this version to be published? If it's estimated to be weeks after the release, even letting us know that would be good so I can start extracting the install scripts to run without the support of this beloved tool.

**Comment by bddenhartog** [comment] 2017-07-08 03:12
Thank you for opening this issue. I've been out of commission for the past week (moving, unpacking etc), but should have some time to conduct testing this weekend. 

That said, it may not be a smooth transition, and a release for F26 could end up taking longer than expected. Generally speaking, you should be able to rely on having the FWH repositories serving fedy for F26 by next Friday (July 14) at the latest.

**Comment by ranjithsiji** [comment] 2017-07-11 14:27
Fedy is not working for Fedora 26

**Comment by bddenhartog** [comment] 2017-07-12 14:47
@ranjithsiji We are working on support for F26.

**Comment by georgelappies** [comment] 2017-07-17 20:47
> @ranjithsiji We are working on support for F26.

Appreciating the work you guys are doing, but any idea when it will be released?

**Comment by bddenhartog** [comment] 2017-07-17 20:52
@georgelappies ideally tonight. currently attempting to resolve an issue with the build workflow.

**Comment by bddenhartog** [comment] 2017-07-17 21:47
Fedy is now released for Fedora 26, and should become generally available over the next few hours as it is distributed. Please feel free to file bugs for packages or installation issues in a new issue.

**Closed by bddenhartog** 2017-07-17 21:47 UTC

**Comment by georgelappies** [comment] 2017-07-18 05:25
> Fedy is now released for Fedora 26

Most excellent, thanks!

**Comment by daniel-wtd** [comment] 2017-07-18 08:00
Hmmm, using the installer from the webpage leads to http404. Can you have another look in it?

**Comment by bddenhartog** [comment] 2017-07-18 16:00
@daniel-wtd This may be due to a caching issue. We're behind a CDN now, and perhaps the 404 response was cached prior to the file existing. I've invalidated the cache, which should propagate within about 15 minutes. I'll be checking on this throughout the day.

**Comment by daniel-wtd** [comment] 2017-07-18 16:24
Can confirm it works for me :)

**Comment by Gouri** [comment] 2017-07-19 17:57
No, It is not, When I give command "sudo sh -c 'curl https://www.folkswithhats.org/installer | bash'" from https://www.folkswithhats.org/

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   985  100   985    0     0   3316      0 --:--:-- --:--:-- --:--:--  3327
Adding repositories...
Installing fedy... Failed to synchronize cache for repo 'Dropbox', disabling.
Last metadata expiration check: 0:00:12 ago on Wednesday 19 July 2017 11:23:49 PM IST.
No package fedy available.
Error: Unable to find a match
FAILED
Please report bugs at https://github.com/folkswithhats/fedy/issues

**Comment by bddenhartog** [comment] 2017-07-19 21:44
@Gouri I am unable to reproduce that on a fresh VM.

Can you please paste the contents of your repostory configuration file? It should be located at `/etc/yum.repos.d/folkswithhats.repo`.

**Comment by biggestchops** [comment] 2017-07-20 02:56
Thanks for the update you guys.

**Comment by Gouri** [comment] 2017-07-20 12:51
@bddenhartog 

the thing is i update everyday and once i upgraded to fedora 26, it was creating problem and i uninstalled it. And the thing is the repo file is also removed somehow. 

So When you asked for the repo file. I checked, and it is not there. So I manually added it and it is working fine now.

Thanks

**Comment by bddenhartog** [comment] 2017-07-20 14:17
@Gouri Ah, I see the issue. You probably ran `dnf remove fedy`, and then manually deleted the repo file.

Our repo file is managed through the `folkswithhats-release` package. In the installation script, we check to see if this package is installed. If it _is not_ installed, then we grab the latest version (which sets up the repo file).

Because you still had the `folkswithhats-release` package installed, the install script made the assumption that the repo file existed. The installation script should probably be refactored to handle edge cases like this in a better fashion - even though this was a user error, it is something that could have been avoided. Thank you for bringing this to my attention!
