### ISSUE TITLE
Error : Archive formats

### ISSUE THREAD

**Issue by PaulimGNU** [folkswithhats/fedy#375] opened 2016-06-27 03:55 UTC
fedy does not install the package Archive formats. I ask for help not only me this error.

**Comment by breadlesscode** [comment] 2016-06-28 08:29
Fedora 24, same here

**Comment by doktor-nick** [comment] 2016-06-30 12:22
Me too for F24 from a clean workstation install. I get:
Failed to synchronize cache for repo 'jgillich-brackets', disabling.
Last metadata expiration check: 1:33:30 ago on Thu Jun 30 20:45:03 2016.
Package cabextract-1.5-4.fc24.x86_64 is already installed, skipping.
Package lzip-1.18-1.fc24.x86_64 is already installed, skipping.
Package p7zip-15.14.1-1.fc24.x86_64 is already installed, skipping.
Package p7zip-plugins-15.14.1-1.fc24.x86_64 is already installed, skipping.
No package unrar available.
Error: Unable to find a match.

I'm also getting the codecs non-install that others are experiencing.

**Comment by PaulimGNU** [comment] 2016-07-01 05:34
error the fedora 24

**Comment by Abhinav1217** [comment] 2016-07-18 14:12
Can't reproduce it. Just tried on a fresh installed F24 on my laptop.

```
flash-plugin.x86_64 11.2.202.632-release                                      

Complete!
Last metadata expiration check: 0:00:42 ago on Mon Jul 18 19:24:00 2016.
Dependencies resolved.
================================================================================
 Package         Arch     Version             Repository                   Size
================================================================================
Installing:
 cabextract      x86_64   1.5-4.fc24          fedora                       48 k
 lzip            x86_64   1.18-1.fc24         updates                      93 k
 p7zip           x86_64   15.14.1-1.fc24      fedora                      678 k
 p7zip-plugins   x86_64   15.14.1-1.fc24      fedora                      987 k
 unrar           x86_64   5.4.2-1.fc24        rpmfusion-nonfree-updates   152 k

Transaction Summary
================================================================================
Install  5 Packages

Total download size: 1.9 M
Installed size: 5.2 M
Downloading Packages:
(1/5): cabextract-1.5-4.fc24.x86_64.rpm          13 kB/s |  48 kB     00:03    
(2/5): p7zip-15.14.1-1.fc24.x86_64.rpm           49 kB/s | 678 kB     00:13    
(3/5): lzip-1.18-1.fc24.x86_64.rpm               73 kB/s |  93 kB     00:01    
(4/5): p7zip-plugins-15.14.1-1.fc24.x86_64.rpm   59 kB/s | 987 kB     00:16    
(5/5): unrar-5.4.2-1.fc24.x86_64.rpm             12 kB/s | 152 kB     00:13    
--------------------------------------------------------------------------------
Total                                            92 kB/s | 1.9 MB     00:21     
warning: /var/cache/dnf/rpmfusion-nonfree-updates-499a581200a0988c/packages/unrar-5.4.2-1.fc24.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID 96ca6280: NOKEY
Importing GPG key 0x96CA6280:
 Userid     : "RPM Fusion nonfree repository for Fedora (24) <rpmfusion-buildsys@lists.rpmfusion.org>"
 Fingerprint: DD75 25B6 184B 0512 AA8C B100 2E59 159B 96CA 6280
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-24
Key imported successfully
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Installing  : lzip-1.18-1.fc24.x86_64                                     1/5 
  Installing  : unrar-5.4.2-1.fc24.x86_64                                   2/5 
  Installing  : p7zip-plugins-15.14.1-1.fc24.x86_64                         3/5 
  Installing  : p7zip-15.14.1-1.fc24.x86_64                                 4/5 
  Installing  : cabextract-1.5-4.fc24.x86_64                                5/5 
  Verifying   : cabextract-1.5-4.fc24.x86_64                                1/5 
  Verifying   : p7zip-15.14.1-1.fc24.x86_64                                 2/5 
  Verifying   : p7zip-plugins-15.14.1-1.fc24.x86_64                         3/5 
  Verifying   : unrar-5.4.2-1.fc24.x86_64                                   4/5 
  Verifying   : lzip-1.18-1.fc24.x86_64                                     5/5 

Installed:
  cabextract.x86_64 1.5-4.fc24        lzip.x86_64 1.18-1.fc24                   
  p7zip.x86_64 15.14.1-1.fc24         p7zip-plugins.x86_64 15.14.1-1.fc24       
  unrar.x86_64 5.4.2-1.fc24          

Complete!
--2016-07-18 19:25:16--  https://www.dropbox.com/install
```

Try to clean the cache and try again. I did get few 404 during install process but mirrors took over and installation went successfully. 

If you are running this on a fresh install, I would suggest that you should run `sudo dnf -y update --refresh && sudo dnf clean all` before running fedy. The problem should be gone. 

I am closing this for now. Reopen if you face this problem again.

**Closed by Abhinav1217** 2016-07-18 14:12 UTC

**Comment by jkandasa** [comment] 2016-11-15 07:48
I too face this issue. I did upgrade from F23 to F24. `dnf update` says,
```
Failed to synchronize cache for repo 'jgillich-brackets', disabling.
```

in my repo I am seeing as follows[File: `/etc/yum.repos.d/_copr_jgillich-brackets.repo`],
```
[jgillich-brackets]
name=Copr repo for brackets owned by jgillich
baseurl=https://copr-be.cloud.fedoraproject.org/results/jgillich/brackets/fedora-$releasever-$basearch/
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://copr-be.cloud.fedoraproject.org/results/jgillich/brackets/pubkey.gpg
enabled=1
enabled_metadata=1
```

**I do not see `fedora-23-x86_64` directory on this url**

![image](https://cloud.githubusercontent.com/assets/1004403/20297275/b7f738d6-ab35-11e6-8b26-12810493dd3b.png)

**Comment by Abhinav1217** [comment] 2016-11-17 08:12
Brackets editor plugin will move to new copr repo this update.
