### ISSUE TITLE
F24 - Multimedia codecs unable to install

### ISSUE THREAD

**Issue by stricte** [folkswithhats/fedy#373] opened 2016-06-24 12:36 UTC
Latest release with installed packages:

fedy.noarch                            4.2.1-1.fc24                @folkswithhats
fedy-core.noarch                       4.2.1-1.fc24                @folkswithhats
fedy-plugins.noarch                    4.2.1-1.fc24                @folkswithhats
fedy.src                               4.2.1-1.fc24                folkswithhats
fedy-font-config.noarch                1.0.1-1.fc24                folkswithhats
fedy-font-config.src                   1.0.1-1.fc24                folkswithhats
fedy-multimedia-codecs.noarch          1.0.1-1.fc24                folkswithhats
fedy-multimedia-codecs.src             1.0.1-1.fc24                folkswithhats

with error: nothing provides amrnb needed by fedy-multimedia-codecs-1.0.1-1.fc24.noarch

**Comment by maufor** [comment] 2016-06-25 08:11
Same problem here...

**Comment by Abhinav1217** [comment] 2016-06-26 06:57
Strange? It did not happen when I tired it first time on fresh install. But now on a VM I get the error. 
Give me some time to work this through.

**Comment by iadr** [comment] 2016-07-15 05:15
I've installed fedy in f24 but when i try to install codecs it inmediatly says that is unable to install

**Comment by Abhinav1217** [comment] 2016-07-18 13:58
Just installed F24 fresh on my laptop. I am installing fedy as i am writing this. I will see if this problem is faced by me.

**Comment by Abhinav1217** [comment] 2016-07-18 14:18
Can't reproduce it. I just successfully installed Multimedia codecs using fedy.
```
Installed:
  GraphicsMagick.x86_64 1.3.24-1.fc24                     OpenEXR-libs.x86_64 2.2.0-5.fc24                  SDL.x86_64 1.2.15-21.fc24                         a52dec-libs.x86_64 0.7.4-20.fc24                     
  amrnb.x86_64 11.0.0.0-2.fc24                            amrwb.x86_64 11.0.0.0-2.fc24                      faac.x86_64 1.28-7.fc24                           faad2.x86_64 1:2.7-8.fc24                            
  faad2-libs.x86_64 1:2.7-8.fc24                          fedy-multimedia-codecs.noarch 1.0.1-1.fc24        ffmpeg-libs.x86_64 1:3.1.1-1.fc24                 fftw-libs-double.x86_64 3.3.4-7.fc24                 
  flac.x86_64 1.3.1-6.fc24                                flite.x86_64 1.3-26.fc24                          game-music-emu.x86_64 0.6.0-8.fc24                gpac-libs.x86_64 1:0.6.1-2.fc24                      
  gstreamer.x86_64 0.10.36-14.fc24                        gstreamer-ffmpeg.x86_64 0.10.13-15.fc24           gstreamer-plugins-bad.x86_64 0.10.23-7.fc24       gstreamer-plugins-bad-free.x86_64 0.10.23-32.fc24    
  gstreamer-plugins-bad-nonfree.x86_64 0.10.23-3.fc24     gstreamer-plugins-base.x86_64 0.10.36-14.fc24     gstreamer-plugins-espeak.x86_64 0.4.0-9.fc24      gstreamer-plugins-fc.x86_64 0.2-12.fc24              
  gstreamer-plugins-good.x86_64 0.10.31-16.fc24           gstreamer-plugins-ugly.x86_64 0.10.19-19.fc24     gstreamer-rtsp.x86_64 0.10.8-11.fc24              gstreamer-tools.x86_64 0.10.36-14.fc24               
  gstreamer1-libav.x86_64 1:1.8.2-1.fc24                  gstreamer1-plugins-bad.x86_64 1:1.8.2-1.fc24      gstreamer1-plugins-ugly.x86_64 1:1.8.2-1.fc24     ilmbase.x86_64 2.2.0-5.fc24                          
  kvazaar-libs.x86_64 0.8.3-1.fc24                        ladspa.x86_64 1.13-16.fc24                        lame.x86_64 3.99.5-5.fc24                         libavdevice.x86_64 1:3.1.1-1.fc24                    
  libbs2b.x86_64 3.1.0-16.fc24                            libchromaprint.x86_64 1.2-4.fc24                  libdc1394.x86_64 2.2.2-5.fc24                     libdca.x86_64 0.0.5-9.fc24                           
  libde265.x86_64 1.0.2-3.503af19.fc24                    libebml.x86_64 1.3.3-3.fc24                       libfc14audiodecoder.x86_64 1.0.3-7.fc24           libkate.x86_64 0.4.1-7.fc24                          
  liblrdf.x86_64 0.5.0-10.fc24                            libmad.x86_64 0.15.1b-18.fc24                     libmatroska.x86_64 1.4.4-2.fc24                   libmfx.x86_64 1.16-1.7adf2e4.fc24                    
  libmimic.x86_64 1.0.4-9.fc24                            libmms.x86_64 0.6.4-4.fc24                        libmodplug.x86_64 1:0.8.8.5-8.fc24                libmp4v2.x86_64 2.1.0-0.6.trunkREV507.fc24           
  libmpcdec.x86_64 1.2.6-16.fc24                          libmpeg2.x86_64 0.5.1-12.fc24                     libofa.x86_64 0.9.3-28.fc24                       librtmp.x86_64 2.4-6.gita107cef.fc24                 
  libssh.x86_64 0.7.3-1.fc24                              libtiger.x86_64 0.3.4-11.fc24                     libvo-aacenc.x86_64 0.1.3-1.fc24                  libwmf-lite.x86_64 0.2.8.4-48.fc24                   
  mesa-libGLES.x86_64 12.0.1-1.fc24                       mjpegtools-libs.x86_64 2.1.0-6.fc24               mpg123-libs.x86_64 1:1.23.3-2.fc24                opencore-amr.x86_64 0.1.3-4.fc24                     
  opencv.x86_64 2.4.12.3-3.fc24                           opencv-core.x86_64 2.4.12.3-3.fc24                openh264-libs.x86_64 1.5.0-2.fc24                 openjpeg-libs.x86_64 1.5.1-16.fc24                   
  qt5-qtwayland.x86_64 5.6.1-1.fc24                       schroedinger.x86_64 1.0.11-10.fc24                spandsp.x86_64 0.0.6-0.15.pre21.fc24              twolame-libs.x86_64 0.3.13-5.fc24                    
  vo-amrwbenc.x86_64 0.1.3-3.fc24                         x264.x86_64 1:0.148-6.a5e06b9.fc24                x265.x86_64 1.9-1.fc24                            xvidcore.x86_64 1.3.4-3.fc24                         
  zbar.x86_64 0.10-26.fc24                                zvbi.x86_64 0.2.35-1.fc24                        

Complete!
Failed to show notifica
```

I am closing this for now. Reopen this if the problem persists again. Try cleaning cache and try again.

**Closed by Abhinav1217** 2016-07-18 14:18 UTC
