### ISSUE TITLE
Arc Icon Theme

### ISSUE THREAD

**Issue by ElvisPresly** [folkswithhats/fedy#392] opened 2016-10-11 05:50 UTC
Add please Arc icon theme
https://github.com/horst3180/arc-icon-theme

**Comment by danstewart** [comment] 2016-10-13 12:43
I can add this tonight. 

@Abhinav1217 @satya164 
Is cloning from git alright or should I try and use wget/curl on the releases?

**Comment by ElvisPresly** [comment] 2016-10-13 14:14
I do not know

**Comment by Abhinav1217** [comment] 2016-10-16 12:43
curl/wget is preferred over git clone because they are available by default on every system, ( and is stated as dependency during fedy install ). Git is not.

**Comment by danstewart** [comment] 2016-10-16 12:54
No bother, I used curl (#393).

**Comment by satya164** [comment] 2016-10-16 13:09
Actually wget is stated as a dependency :)

**Comment by danstewart** [comment] 2016-10-16 13:11
@satya164 but curl isn't? No bother, I can change it.

**Comment by satya164** [comment] 2016-10-16 13:14
@danstewart Yeah. Thank you.

**Comment by bertrandbo** [comment] 2016-12-12 20:03
Hi,

Note that arc-icon-theme is available in a [copr repository](https://copr.fedorainfracloud.org/coprs/heikoada/gtk-themes/). This repository seems quite up-to-date and well maintained.

The downside is that it relies on the copr's owner to package updates and build for new Fedora releases (which is the problem for Paper theme in #407 ).

But the good point is that DNF would keep the icon theme up-to-date, which is not the case with a wget-based installation. And, using that copr repository would also fix #407

**Comment by bheru27** [comment] 2016-12-12 20:07
Please add the respective changes and submit a PR so it will be added on the new build today

**Comment by bertrandbo** [comment] 2016-12-12 21:14
@bheru27 As the copr would be used in two plugins, how to properly manage the repository deactivation ?

**Comment by bheru27** [comment] 2016-12-12 22:06
Is the same used by both? I would think its better to remover the old repo http://dnf-plugins-core.readthedocs.io/en/latest/copr.html with dnf copr remove  guy/repo where it needs to be done. New users wont be affected but that way old ones can remove it and install the new one without problems.

**Comment by Abhinav1217** [comment] 2017-01-13 15:44
Can we close this? have we moved to new copr?

**Comment by dralley** [comment] 2017-02-01 19:29
Any updates on this?

**Comment by danstewart** [comment] 2017-02-03 09:23
@dralley Not yet.

@bheru27 Not sure what you meant about the two copr repos? I think the best way to handle it is to just run the test for the other plugin and if it's enabled don't disable the copr - though it's a little clunky.

Any ideas?

**Comment by Xmetalfanx** [comment] 2017-03-12 03:30
Reading other's posts ... using copr over the git repo (via say curl or wget) would be better?  ... yeah I see that dnf would keep it up to date though your getting from the "developer" of the icon pack and theme themselves via git.

Just curious

**Comment by danstewart** [comment] 2017-03-12 19:33
@Xmetalfanx Yeah, copr would be better because, as you said, it will stay up to date.

The reason this hasn't been added yet is we currently don't have any logic for handling disabling of copr repos that are used in multiple plugins - since we disable the repo in the uninstall script this would break updates for plugins that use the same repo. Still looking into solutions for this though.

**Comment by danstewart** [comment] 2017-03-12 19:37
I've raised the multiple plugins using one repo as a separate issue - #446

**Comment by user501254** [comment] 2017-05-13 19:56
Hi all,

I have made Pull request which makes use of my personal Copr Repository.
Issues with rpm packaging can be reported over [here](https://github.com/user501254/packaging).

**Closed** 2017-05-14 17:16 UTC
Labels: area/plugins, in progress, type/feature

**Comment by xasx** [comment] 2017-06-21 08:07
Installed this via Fedy.

Does not show up in gnome-tweak-tool. Any idea why or how to make it work?

**Comment by user501254** [comment] 2017-06-21 16:27
@xasx 
You might want to restart your machine and see if it works. 
Alternatively, does `gsettings set org.gnome.desktop.interface icon-theme 'Arc'` work?

**Comment by bddenhartog** [comment] 2017-06-21 21:10
quote @user501254
> You might want to restart your machine and see if it works. 
> Alternatively, does `gsettings set org.gnome.desktop.interface icon-theme 'Arc'` work?

Restarting the machine is not necessary, you simply need to reload `gnome-shell`. This can be accomplished a few different ways (listed in order of ease):

* Press `Alt+F2` to open the `Run Command` window, type in `r`, and press enter. This will reload Gnome.
* From the command line, execute `gnome-shell --replace`. This replaces the running window manager.
* Log out and back in again. Gnome user sessions are closed on logout.
* Restart your machine. This accomplishes the task in a similar way to logging out and back in again.

**Comment by bddenhartog** [comment] 2017-06-21 21:13
quote @user501254

> You might want to restart your machine and see if it works.
> Alternatively, does gsettings set org.gnome.desktop.interface icon-theme 'Arc' work?

Restarting the machine is not necessary, you simply need to reload `gnome-shell`. This can be accomplished a few different ways (listed in order of ease):

* Press `Alt+F2` to open the _Run Command_ prompt, type in `r`, and press `enter`. This will reload Gnome.
* From the command line, execute `gnome-shell --replace`. This replaces the running window manager.
* Log out and back in again. Gnome user sessions are closed on logout.
* Restart your machine. This accomplishes the task in a similar way to logging out and back in again.

Reloading `gnome-shell` is necessary because extensions are only loaded once per session, and not dynamically watched.

Hope this helps, @xasx.

**Comment by xasx** [comment] 2017-06-22 06:01
Restarting did _not_ help, unfortunately. Arc icon theme still did not show up.

Then I tried the `gsettings` way, the icon theme was changed as intended.

Starting `gnome-tweak-tool` then revealed a whole bunch of other available icon packs (there was only one shown before). Sorry for concerning you here - this must either be system-specific or a bug in tweak tool.

**Comment by bddenhartog** [comment] 2017-06-22 07:46
> Restarting did not help, unfortunately. Arc icon theme still did not show
up.
>
> Then I tried the gsettings way, the icon theme was changed as intended.

While it's no surprise that using `gsettings` worked, I'm a bit curious as
to why reloading gnome-shell _didn't_ work. That's all I've ever had to do
in order to load new extensions. Definitely sounds environment-specific,
so, glad you got it worked out!

> Starting gnome-tweak-tool then revealed a whole bunch of other available
icon packs (there was only one shown before).

This is _probably_ because you reloaded gnome, and not a result of setting
the option via `gsettings` directly.

**Comment by bddenhartog** [comment] 2017-06-22 08:00
> Restarting did not help, unfortunately. Arc icon theme still did not show up.
>
> Then I tried the gsettings way, the icon theme was changed as intended.

While it's no surprise that using `gsettings` worked, I'm a bit curious as
to why reloading gnome-shell _didn't_ work. That's all I've ever had to do
in order to load new extensions. Definitely sounds environment-specific,
so, glad you got it worked out!

> Starting gnome-tweak-tool then revealed a whole bunch of other available icon packs (there was only one shown before).

This is _probably_ because you reloaded gnome, and not a result of setting
the option via `gsettings` directly.

**Comment by xasx** [comment] 2017-06-22 08:06
@bddenhartog To make it clear:
* restart
   &rarr; only 'Paper' is shown as available icon theme
* close tweak tool, use `gsettings`, start tweak tool
   &rarr; shows up, along with all the others
* select 'Paper' icon theme in tweak tool
   &rarr; all other icon themes are gone again

To sum it up, unless I select the 'Paper' icon theme, the others are shown. Especially 'Arc' as well.

Further info: reloading gnome shell is prevented here due to F25 being based on Wayland.

**Comment by bddenhartog** [comment] 2017-06-22 15:53
> * restart
>    &rarr; only 'Paper' is shown as available icon theme
> * close tweak tool, use `gsettings`, start tweak tool
>    &rarr; shows up, along with all the others
> * select 'Paper' icon theme in tweak tool
>    &rarr; all other icon themes are gone again

Is this a reproducible workflow for you?

**Comment by user501254** [comment] 2017-06-22 16:01
@bddenhartog 
Just saying to restart the machine seemed simpler :stuck_out_tongue: 
Thanks for typing that out!
