### ISSUE TITLE
Curl does not follow the redirect 301 to download your repository-RPM 

### ISSUE THREAD

**Issue by abalg** [folkswithhats/fedy#444] opened 2017-03-09 10:46 UTC
In my fed25 installation curl does not follow the HTTP-redirect to the RPM-Package setting up your repository. So cut and paste of your code from the website does not work as the "fedy" repository is not getting installed thus "fedy" is not found an cannot be installed ...

I assueme adding 
   -L, --location
to your code snippet should do the trick

**Comment by bddenhartog** [comment] 2017-03-09 16:16
`curl` is not used in the `installer` script; we _do_ have `https://folkswithhats.org` in the `dnf` command (which gets redirected to `https://www...`), but `dnf` properly follows the redirect.

You must be pasting an incorrect command. Executing what is on the front page works properly for me.

**Comment by bddenhartog** [comment] 2017-03-09 16:25
Duplicate of #436.

**Closed by bddenhartog** 2017-03-09 16:25 UTC
Labels: type/duplicate

**Comment by abalg** [comment] 2017-03-11 10:29
You did not get me correctly - It's actually not the installer-script itself that can be downloaded BUT the snippet "curl https://www.folkswithhats.org/installer | sudo bash". Curl (maybe just a specific version) did not follow the HTTP-301 redirect but just sent the HTML telling me to redirect itself to the bash.

Seems as if you've fixed that already or curl was updated in the meantime - now it works

**Comment by abalg** [comment] 2017-03-11 10:30
Before "curl -l https://www.folkswithhats.org/installer | sudo bash " did the trick for me ...

**Comment by bddenhartog** [comment] 2017-03-11 16:27
I'm not sure what to tell you; `https://www.folkswithhats.org/installer` is the URI that's being served - it doesn't redirect anywhere. Perhaps you manually typed out the command and missed the `https` or `www`? 

In any case, glad it's resolved now.

**Comment by bddenhartog** [comment] 2017-03-11 16:30
And yes - like `wget`, `curl` does not follow redirects automatically. You need to specify that you want that behavior.
