### ISSUE TITLE
[F22] Popcorn time install fails

### ISSUE THREAD

**Issue by DoctorJellyface** [folkswithhats/fedy#243] opened 2015-07-24 16:26 UTC
Title pretty much self-explanatory. If you need any more info just ask, but I don't know how long I'll be on fedora.

**Comment by cadesalaberry** [comment] 2015-07-24 17:16
Hi there, I submitted https://github.com/satya164/fedy/pull/241 to fix it. Waiting on @satya164 to check it.

Meanwhile, you can:
```bash
sudo vi /usr/share/fedy/plugins/popcorntime.plugin/install.sh
# Comment out the line
#  URL=$(wget "https://popcorntime.io" -O - | grep -o "https://get.popcorntime.io/build/Popcorn-Time-[0-9.]*-Linux${ARCH}.tar.xz" | head -n 1)
# Replace it with
 URL=$(wget "https://popcorntime.io" -O - | grep -o "https://get.popcorntime.io/build/\S*${ARCH}.tar.xz" | head -n 1) 
```

**Comment by DoctorJellyface** [comment] 2015-07-24 18:57
Thanks, worked perfectly!

**Comment by Rohan62442** [comment] 2015-08-19 17:10
The pull request for this has been merged. Can someone confirm if the issue is solved?

**Comment by improoviz** [comment] 2015-08-23 11:31
Thanks for the solved. It works.

**Closed** 2015-08-24 16:03 UTC

**Comment by gitgt** [comment] 2015-09-22 10:24
With fedy-3.2.1, which should be the latest version as of today, I can't install Popcorn.

**Comment by cadesalaberry** [comment] 2015-09-22 13:21
The latest is [`4.0.5`](https://github.com/folkswithhats/fedy/releases/tag/v4.0.5). You should try and upgrade.

**Comment by gitgt** [comment] 2015-09-22 16:06
Sorry. Same as in issue #240  ozon-os.com repos server is down, and Fedy couldn't be updated. I pulled from git and Popcorn is OK now. Thank you.
